services:  
  seasearch:  
    image: ${SEASEARCH_IMAGE:-seafileltd/seasearch:latest}
    container_name: seasearch  
    volumes:  
      - ${SEASEARCH_DATA_PATH}:/opt/seasearch/data  
    ports:  
      - "4080:4080" 
    environment: 
      - ZINC_FIRST_ADMIN_USER=${ZINC_FIRST_ADMIN_USER}
      - ZINC_FIRST_ADMIN_PASSWORD=${ZINC_FIRST_ADMIN_PASSWORD}
    networks:
      - frontend-net
      - backend-scheduler-net


networks:
  frontend-net:
    name: frontend-net
  backend-scheduler-net:
    name: backend-scheduler-net
