services:  
  seasearch:  
    image: ${SEASEARCH_IMAGE:-seafileltd/seasearch:latest}
    container_name: seasearch  
    volumes:  
      - ${SEASEARCH_DATA_PATH}:/opt/seasearch/data  
    ports:  
      - "4080:4080" 
    environment: 
      - ZINC_FIRST_ADMIN_USER=${ZINC_FIRST_ADMIN_USER}
      - ZINC_FIRST_ADMIN_PASSWORD=${ZINC_FIRST_ADMIN_PASSWORD}
      - GIN_MODE=${GIN_MODE:-release}
      - ZINC_WAL_ENABLE=${ZINC_WAL_ENABLE:-true}
      - ZINC_STORAGE_TYPE=${ZINC_STORAGE_TYPE}
      - ZINC_SHARD_NUM=${ZINC_SHARD_NUM}
      - ZINC_MAX_OBJ_CACHE_SIZE=${ZINC_MAX_OBJ_CACHE_SIZE}
      - ZINC_S3_ACCESS_ID=${ZINC_S3_ACCESS_ID}
      - ZINC_S3_USE_V4_SIGNATURE=${ZINC_S3_USE_V4_SIGNATURE}
      - ZINC_S3_ACCESS_SECRET=${ZINC_S3_ACCESS_SECRET}
      - ZINC_S3_ENDPOINT=${ZINC_S3_ENDPOINT}
      - ZINC_S3_USE_HTTPS=${ZINC_S3_USE_HTTPS}
      - ZINC_S3_PATH_STYLE_REQUEST=${ZINC_S3_PATH_STYLE_REQUEST}
      - ZINC_S3_AWS_REGION=${ZINC_S3_AWS_REGION}
      - ZINC_SERVER_MODE=${ZINC_SERVER_MODE}
      - ZINC_CLUSTER_ID=${ZINC_CLUSTER_ID}
      - ZINC_ETCD_USERNAME=${ZINC_ETCD_USERNAME}
      - ZINC_ETCD_PASSWORD=${ZINC_ETCD_PASSWORD}
      - ZINC_CLUSTER_PROXY_LOG_DIR=${ZINC_CLUSTER_PROXY_LOG_DIR:-/opt/seasearch/data/log}
      - ZINC_CLUSTER_PROXY_HOST=${ZINC_CLUSTER_PROXY_HOST:-0.0.0.0}
      - ZINC_CLUSTER_PROXY_PORT=${ZINC_CLUSTER_PROXY_PORT:-4082}
      - ZINC_ETCD_ENDPOINTS=${ZINC_ETCD_ENDPOINTS:-127.0.0.1:2379}
      - ZINC_ETCD_PREFIX=${ZINC_ETCD_PREFIX:-/zinc}
      - ZINC_MAX_DOCUMENT_SIZE=${ZINC_MAX_DOCUMENT_SIZE:-1m}
      - ZINC_CLUSTER_MANAGER_ADDR=${ZINC_CLUSTER_MANAGER_ADDR:-127.0.0.1:4081}
      - ZINC_CLUSTER_MANAGER_LOG_DIR=${ZINC_CLUSTER_MANAGER_LOG_DIR:-/opt/seasearch/data/log}
      - ZINC_CLUSTER_MANAGER_HOST=${ZINC_CLUSTER_MANAGER_HOST:-0.0.0.0}
      - ZINC_CLUSTER_MANAGER_PORT=${ZINC_CLUSTER_MANAGER_PORT:-4081}
      - ZINC_CLUSTER_MANAGER_ETCD_ENDPOINTS=${ZINC_CLUSTER_MANAGER_ETCD_ENDPOINTS:-127.0.0.1:2379}
      - ZINC_CLUSTER_MANAGER_ETCD_PREFIX=${ZINC_CLUSTER_MANAGER_ETCD_PREFIX:-/zinc}
      - ZINC_LOG_OUTPUT=${ZINC_LOG_OUTPUT:-true}
      - ZINC_LOG_DIR=${ZINC_LOG_DIR:-/opt/seasearch/data/log}
      - ZINC_LOG_LEVEL=${ZINC_LOG_LEVEL:-debug}
    networks:
      - frontend-net
      - backend-scheduler-net


networks:
  frontend-net:
    name: frontend-net
  backend-scheduler-net:
    name: backend-scheduler-net
